import { AlertTriangle, ArrowLeft, BookOpen, Home, RefreshCw, ServerCrash, WifiOff } from 'lucide-react';
import { useRouter } from '@/context/RouterContext';

export function NotFound() {
  const { navigate } = useRouter();
  return <main className="flex min-h-[calc(100vh-72px)] items-center justify-center px-5"><div className="text-center"><div className="relative mx-auto mb-8 flex h-28 w-28 items-center justify-center"><div className="absolute inset-0 animate-pulse rounded-full bg-cyan-100 dark:bg-cyan-950/50" /><div className="relative flex h-20 w-20 items-center justify-center rounded-full border border-cyan-200 bg-white text-cyan-500 shadow-xl dark:border-cyan-900 dark:bg-slate-900"><WifiOff className="h-8 w-8" /></div></div><p className="font-mono text-xs font-bold uppercase tracking-[0.2em] text-cyan-600 dark:text-cyan-400">Error 404</p><h1 className="mt-3 text-4xl font-bold tracking-[-0.05em] text-slate-950 sm:text-5xl dark:text-white">Endpoint not found</h1><p className="mx-auto mt-4 max-w-md text-sm leading-6 text-slate-500 dark:text-slate-400">The endpoint you are looking for doesn't exist or may have been moved. Check the URL and try again.</p><div className="mt-8 flex justify-center gap-3"><button onClick={() => navigate('/')} className="flex items-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white transition-colors hover:bg-slate-800 dark:bg-white dark:text-slate-950"><Home className="h-4 w-4" /> Homepage</button><button onClick={() => navigate('/docs')} className="flex items-center gap-2 rounded-xl border border-slate-300 px-5 py-3 text-sm font-semibold text-slate-700 transition-colors hover:bg-slate-50 dark:border-slate-700 dark:text-slate-200 dark:hover:bg-slate-800"><BookOpen className="h-4 w-4" /> Documentation</button></div></div></main>;
}

export function ServerError() {
  const { navigate } = useRouter();
  return <main className="flex min-h-[calc(100vh-72px)] items-center justify-center px-5"><div className="text-center"><div className="relative mx-auto mb-8 flex h-28 w-28 items-center justify-center"><div className="absolute inset-0 rounded-full bg-red-100 dark:bg-red-950/40" /><div className="relative flex h-20 w-20 items-center justify-center rounded-full border border-red-200 bg-white text-red-500 shadow-xl dark:border-red-900 dark:bg-slate-900"><ServerCrash className="h-8 w-8" /></div></div><p className="font-mono text-xs font-bold uppercase tracking-[0.2em] text-red-500">Error 500</p><h1 className="mt-3 text-4xl font-bold tracking-[-0.05em] text-slate-950 sm:text-5xl dark:text-white">Something went wrong</h1><p className="mx-auto mt-4 max-w-md text-sm leading-6 text-slate-500 dark:text-slate-400">Our servers ran into an unexpected issue. Your request was not completed, but our team has been notified.</p><div className="mt-8 flex justify-center gap-3"><button onClick={() => window.location.reload()} className="flex items-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white transition-colors hover:bg-slate-800 dark:bg-white dark:text-slate-950"><RefreshCw className="h-4 w-4" /> Try again</button><button onClick={() => navigate('/')} className="flex items-center gap-2 rounded-xl border border-slate-300 px-5 py-3 text-sm font-semibold text-slate-700 transition-colors hover:bg-slate-50 dark:border-slate-700 dark:text-slate-200 dark:hover:bg-slate-800"><ArrowLeft className="h-4 w-4" /> Go back</button></div><div className="mt-10 flex items-center justify-center gap-2 text-xs text-slate-400"><AlertTriangle className="h-3.5 w-3.5" /> API status: <span className="font-semibold text-emerald-500">Operational</span></div></div></main>;
}
